config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'static_pages/home'
  get 'static_pages/help'

  get  'static_pages/home'
  get  'static_pages/help', as: 'help_page'
  get  'static_pages/contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # root 'application#hello'
  root "static_pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/register", to: "user#register"
  post "/register", to: "user#register_post"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  namespace :admin do
    resources :post, :user
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© Rails Template <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>

  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Rails Template", root_path, class: "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= navbar_link_to("Home",
                           root_path,
                           active_when: { controller: "home" }) %>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>

        <% else %>

          <li><%= link_to "Log in", login_path %></li>
          <li>
            <%= link_to("Đăng Ký", signup_path) %>
          </li>

        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% else %>
    <h1>Untitled</h1>
    <p>Don’t forget to set <code>provide(:title)</code> for this view!</p>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>