config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'static_pages/home'
  get 'static_pages/help'

  get  'static_pages/home'
  get  'static_pages/help', as: 'help_page'
  get  'static_pages/contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :microposts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # root 'application#hello'
  root "static_pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/register", to: "user#register"
  post "/register", to: "user#register_post"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  namespace :admin do
    resources :post, :user
  end

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  content    :text(65535)
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  picture    :string(255)
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_microposts_on_user_id                 (user_id)
#  index_microposts_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  mount_uploader :picture, PictureUploader

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def index
    #@microposts = current_user.microposts
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  #########       private       #########
  # micropost_params
  # correct_user
  #
  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="<%= micropost.user.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <%= image_tag micropost.picture.url if micropost.picture? %>
  <span class="timestamp">
<!--    Posted <%#= time_ago_in_words(micropost.created_at) %> ago.-->
    Posted ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete, data: { confirm: "Bạn muốn xoá?"} %>
    <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, "Editing micropost") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/microposts/index.html.erb
<% provide(:title, "Listing microposts") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td>
          <div class="btn-group">
            <%= link_to micropost, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_micropost_path(micropost), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to micropost, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this micropost?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to new_micropost_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Micropost") %>
<% end %>

app/views/microposts/new.html.erb
<% provide(:title, "New micropost") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/microposts/show.html.erb
<% provide(:title) do %>
  Micropost #<%= @micropost.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Content</th>
      <td><%= @micropost.content %></td>
    </tr>
    <tr>
      <th class="col-sm-2">User</th>
      <td><%= @micropost.user_id %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_micropost_path(@micropost), class: "btn btn-primary" %>
  <%= link_to "Back", microposts_path, class: "btn btn-link" %>
</p>